### ISSUE TITLE
debug and pprint not working with pydantic classes

### ISSUE THREAD

**Issue by ludwig-weiss** [samuelcolvin/python-devtools#54]
Hi,

thanks for `devtools` I use it quite a lot.
Now I stumbled over the following:

```python
>>> from devtools import debug

>>> class W:
...     pass

>>> debug(W)
<stdin>:1 <module> (no code context for debug call, code inspection impossible)
    <class '__main__.W'> (type)

>>> class W(:
...     pass
>>> from pydantic import BaseModel

>>> debug(BaseModel)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/weissl/.pyenv/versions/3.8.2/envs/cauldron/lib/python3.8/site-packages/devtools/debug.py", line 122, in __call__
    s = d_out.str(highlight)
  File "/Users/weissl/.pyenv/versions/3.8.2/envs/cauldron/lib/python3.8/site-packages/devtools/debug.py", line 85, in str
    return prefix + '\n    ' + '\n    '.join(a.str(highlight) for a in self.arguments)
  File "/Users/weissl/.pyenv/versions/3.8.2/envs/cauldron/lib/python3.8/site-packages/devtools/debug.py", line 85, in <genexpr>
    return prefix + '\n    ' + '\n    '.join(a.str(highlight) for a in self.arguments)
  File "/Users/weissl/.pyenv/versions/3.8.2/envs/cauldron/lib/python3.8/site-packages/devtools/debug.py", line 45, in str
    s += pformat(self.value, indent=4, highlight=highlight)
  File "/Users/weissl/.pyenv/versions/3.8.2/envs/cauldron/lib/python3.8/site-packages/devtools/prettier.py", line 80, in __call__
    self._format(value, indent_current=indent, indent_first=indent_first)
  File "/Users/weissl/.pyenv/versions/3.8.2/envs/cauldron/lib/python3.8/site-packages/devtools/prettier.py", line 94, in _format
    gen = pretty_func(fmt=fmt, skip_exc=SkipPretty)
  File "pydantic/utils.py", line 263, in pydantic.utils.Representation.__pretty__
TypeError: __pretty__() takes exactly 2 positional arguments (0 given)

__pretty__() takes exactly 2 positional arguments (0 given)

>>> class W(BaseModel):
...     pass

>>> debug(W)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/weissl/.pyenv/versions/3.8.2/envs/cauldron/lib/python3.8/site-packages/devtools/debug.py", line 122, in __call__
    s = d_out.str(highlight)
  File "/Users/weissl/.pyenv/versions/3.8.2/envs/cauldron/lib/python3.8/site-packages/devtools/debug.py", line 85, in str
    return prefix + '\n    ' + '\n    '.join(a.str(highlight) for a in self.arguments)
  File "/Users/weissl/.pyenv/versions/3.8.2/envs/cauldron/lib/python3.8/site-packages/devtools/debug.py", line 85, in <genexpr>
    return prefix + '\n    ' + '\n    '.join(a.str(highlight) for a in self.arguments)
  File "/Users/weissl/.pyenv/versions/3.8.2/envs/cauldron/lib/python3.8/site-packages/devtools/debug.py", line 45, in str
    s += pformat(self.value, indent=4, highlight=highlight)
  File "/Users/weissl/.pyenv/versions/3.8.2/envs/cauldron/lib/python3.8/site-packages/devtools/prettier.py", line 80, in __call__
    self._format(value, indent_current=indent, indent_first=indent_first)
  File "/Users/weissl/.pyenv/versions/3.8.2/envs/cauldron/lib/python3.8/site-packages/devtools/prettier.py", line 94, in _format
    gen = pretty_func(fmt=fmt, skip_exc=SkipPretty)
  File "pydantic/utils.py", line 263, in pydantic.utils.Representation.__pretty__
TypeError: __pretty__() takes exactly 2 positional arguments (0 given)

__pretty__() takes exactly 2 positional arguments (0 given)

>>>
```

Could you please give me a hint what I am doing wrong here?

**Comment by samuelcolvin** [comment]
hopefully this is fixed by #52. Please could you try master to confirm.

If so, I'll release a new version soon.

**Comment by ludwig-weiss** [comment]
It is a little bit better with master.
It prints a warning.
`pprint` is still failing

```python
>>> from devtools import debug

>>> class W:
...     pass

>>> debug (W)
<stdin>:1 <module> (no code context for debug call, code inspection impossible)
    <class '__main__.W'> (type)

>>> from pydantic import BaseModel

>>> debug(BaseModel)
<stdin>:1 <module> (no code context for debug call, code inspection impossible)
    <class 'pydantic.main.BaseModel'> (ModelMetaclass)
    !!! error pretty printing value: TypeError('__pretty__() takes exactly 2 positional arguments (0 given)')

>>> from devtools import pprint

>>> pprint(BaseModel)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/weissl/Devel/iti/python-devtools/devtools/prettier.py", line 239, in pprint
    print(pformat(s, highlight=highlight), file=file, flush=True)
  File "/Users/weissl/Devel/iti/python-devtools/devtools/prettier.py", line 82, in __call__
    self._format(value, indent_current=indent, indent_first=indent_first)
  File "/Users/weissl/Devel/iti/python-devtools/devtools/prettier.py", line 100, in _format
    gen = pretty_func(fmt=fmt, skip_exc=SkipPretty)
  File "pydantic/utils.py", line 263, in pydantic.utils.Representation.__pretty__
TypeError: __pretty__() takes exactly 2 positional arguments (0 given)

__pretty__() takes exactly 2 positional arguments (0 given)

>>> class W(BaseModel):
...     pass

>>> debug(W)
<stdin>:1 <module> (no code context for debug call, code inspection impossible)
    <class '__main__.W'> (ModelMetaclass)
    !!! error pretty printing value: TypeError('__pretty__() takes exactly 2 positional arguments (0 given)')

>>> pprint(W)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/weissl/Devel/iti/python-devtools/devtools/prettier.py", line 239, in pprint
    print(pformat(s, highlight=highlight), file=file, flush=True)
  File "/Users/weissl/Devel/iti/python-devtools/devtools/prettier.py", line 82, in __call__
    self._format(value, indent_current=indent, indent_first=indent_first)
  File "/Users/weissl/Devel/iti/python-devtools/devtools/prettier.py", line 100, in _format
    gen = pretty_func(fmt=fmt, skip_exc=SkipPretty)
  File "pydantic/utils.py", line 263, in pydantic.utils.Representation.__pretty__
TypeError: __pretty__() takes exactly 2 positional arguments (0 given)

__pretty__() takes exactly 2 positional arguments (0 given)

>>>
```

**Comment by samuelcolvin** [comment]
Which version of python are you on, some subtle undocumented changes in 3.8.

**Comment by ludwig-weiss** [comment]
I tried with 3.8 but am now on 3.7.7

```bash
$ python -V 
Python 3.7.7
```

**Comment by samuelcolvin** [comment]
Should fixed by #59 (still needs tests). Please check that works for you.

The problem was cythonized code breaking my check for bound methods.

**Comment by ludwig-weiss** [comment]
Thank you very much for the quick help.
This is indeed solved now
